### PR TITLE
Fix the /oic/res response to align with the spec

### PR DESCRIPTION
**Pull request by nagineni**
* Fix the /oic/res response to align with the spec
* Expose endpoints information

### CODE REVIEW

**Comment by poussa** [comment]
What iotivity-node version we need for this? Should we update that to the `package.json` ?

**Comment by xiaoyu3x** [comment]
hello
I just verified this PR with `iotivity-node->1.3.1-pre-1.3.1-RC6-0` and this PR is OK.

**Comment by nagineni** [comment]
> I just verified this PR with iotivity-node->1.3.1-pre-1.3.1-RC6-0 and this PR is OK.

Changes in this PR are well guarded with 'if' condition and that's the reason you are not seeing any issues. As I mentioned in my previous comment, updating  iotivity-node to latest (i.e 1.3.1-pre-1.3.1-RC6-0) will break the GET and POST functionality.

**Comment by nagineni** [comment]
These changes are now ready for review. I've tested with the latest version of iotivity-node 1.3.1-1. Discovery, GET, POST and OBS features are working fine after provisioning. 

API:
```sh
# Resource discovery (/oic/res)
./oic-get "/res"

# Device discovery discovery (/oic/d)
./oic-get "/d"

# Platform discovery (/oic/p)
./oic-get "/p"

# Resource get (/a/light?di=<Device ID>&ep=<Origin of the resource>&pri=<Priority of the endpoint>)
# http://localhost:8000/api/oic/a/light?di=12345678-1234-1234-1234-123456789012&ep=coaps://<...>&pri=1
./oic-get "/a/light?di=<di>&ep=<ep>&pri=<pri>"

# Resource get with query filter (/a/light?di=<Device ID>&ep=<Origin of the resource>&pri=<Priority of the endpoint> with power less than 50)
./oic-get "/a/light?di=?di=<di>&ep=<ep>&pri=<pri>&power<50"

# Resource observe (/a/light?di=<Device ID>&obs=1&ep=<Origin of the resource>&pri=<Priority of the endpoint>)
./oic-get "/a/light?di=<di>&obs=1&ep=<ep>&pri=<pri>"
```

**Comment by nagineni** [comment]
@poussa PTAL

**Comment by xiaoyu3x** [comment]
hello, @nagineni 
I just wanted to verify this PR, but I encountered a issue when executing command 'npm install' to configure environment.
The following is issue:
selection_002
 
But this issue isn't reproduced when using commit [d0a037e](https://github.com/intel/iot-rest-api-server/commit/d0a037ebe469264c0a4f3ae4386bd9fe3876e216)

Did you meet this issue when you tested this PR?
Do you a good suggestion to help me avoid or resolve this issue?

**Comment by poussa** [comment]
Can you add one more commit which changes the version to 0.7.0

**Comment by nagineni** [comment]
Hi @xiaoyu3x, You need to establish secured communications between OCF server and REST API Server before trying to access(GET/POST) the resource. 
Instructions are explained in the README here - https://github.com/intel/iotivity-node/blob/master/js/README.md

**Comment by nagineni** [comment]
Looks like there is an issue in accessing the secured resources over Ipv6 address on Linux also.
https://jira.iotivity.org/browse/IOT-2705

**Comment by poussa** [comment]
IPv6 issue is know and documented. We'll merge this now and wait for IPv6 fix,

**Pull request merged**
